version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    assigness:
      - "kuanhn"
    commit-message:
      prefix: "chore: "
